### ISSUE TITLE
Adding Ark

### ISSUE THREAD

**Issue by vRobM** [ummjackson/awdy#11]
Adding in .zip form as .yml is not supported by Github.
[ark.zip](https://github.com/ummjackson/awdy/files/1892199/ark.zip)

**Comment by ummjackson** [comment]
Hi @vRobM - please submit a pull request for this. I don't want to open random zip files :)

**Comment by vRobM** [comment]
How about this?
[ark.yml.txt](https://github.com/ummjackson/awdy/files/1892906/ark.yml.txt)
