### ISSUE TITLE
IOTA

### ISSUE THREAD

**Issue by johndomenic** [ummjackson/awdy#17]
Hi, 

Regarding are miners/voters incentivized, the answer in IOTA is yes. In order to have your transaction validated you need to validate two previous transactions and perform a small amount of PoW. How is this not motivation? You **have** to do this in order to make a transaction. If that isn't motivation, I don't know what is.

Regarding "# of entities in control of >50% of voting/mining power", this is more complicated than a simple count, especially so when IOTA no longer relies on the coordinator, but IOTA with the coordinator you can argue it is one. I won't nitpick about this. 

"% of money supply held by top 100 accounts" is a bit misleading for all of the currencies. All it gives is a lower bound on the intuition you are trying to quantify. Anyone can break up their balance into multiple wallets. I don't know how useful this number is, especially if we try to use it to compare respective currencies against each other.

Regarding Client codebase and #number of public nodes, Carriota nodes are 1) not all public, and 2) do not constitute all the full nodes. To make it more accurate you could include _only_ the truly public Full Nodes, of which there are something like 20-30 https://iota.dance/nodes ... and then change the other client codebase stat to say # of client codebases that account for > 90% of the **public full** nodes. Then the number would be 1. I also recommend rewording it because it is kind of confusing as written. 

In IOTA there is manual tethering for Full Nodes, so it is impossible to know how many full nodes there are, and what client they are running (there are other clients, i.e. https://github.com/thibault-martinez/iota.lib.cpp, impossible to know how many full nodes are using them ). Carriota is just a client to enable trust/reputation based automatic tethering. So all that gives us is a lower bound on the number of full nodes. 

Thanks,
John

**Comment by ummjackson** [comment]
@johndomenic Great points, thanks for the info - can you submit a pull request that updates these values for IOTA?
