### ISSUE TITLE
XRP % of money supply held by top 100 accounts calculation

### ISSUE THREAD

**Issue by rloomba** [ummjackson/awdy#21]
what if there is XRP that is "out of circulation" in any of the top 100 accounts? Does that make the current 98% value inaccurate?

**Comment by rloomba** [comment]
> Would putting bitcoins on a paper wallet make it "out of circulation"?
no.

> How about the hodl smart contracts that lock up your ethereums?
no.

So are you suggesting that the total supply should be 98 billion?

**Comment by Badoot** [comment]
XRP's total supply is 100 billion. 

55 billion were locked up in escrow.
https://ripple.com/insights/ripple-escrows-55-billion-xrp-for-supply-predictability/

According to Ripple.com:
TOTAL XRP HELD BY RIPPLE:   7,114,004,047
TOTAL XRP DISTRIBUTED:   39,178,259,468*
TOTAL XRP PLACED IN ESCROW:  53,700,000,024
https://ripple.com/xrp/market-performance/

So according to Ripple.com: XRP held by Ripple + XRP distributed = ~46.3 billion total in circulation

This site being used as a source reports 47.3 billion total: https://ledger.exposed/rich-stats

If we call that close enough, according to that page:

60 accounts have ~36 billion XRP / 47 billion = 77%
100 accounts have ~38 billion XRP / 47 billion = 81%

**Comment by Badoot** [comment]
Jackson made a good point in his [Crypto Weekly](https://www.youtube.com/watch?v=QPfLQB9XcrM) live stream, in that the 55 billion in escrow are ultimately owned by Ripple.  So, 93% of the 100 billion XRP are in 100 accounts.

**Comment by WietseWind** [comment]
This is discussed in PR #29 and #31
