### ISSUE TITLE
Some info about Dash is not quite accurate

### ISSUE THREAD

**Issue by UdjinM6** [ummjackson/awdy#22]
https://github.com/ummjackson/awdy/blob/a7fb4f051cb9373209fec380c25ec297c7090206/_data/coins/dash.yml#L14

>notes: Dash also utilizes PoS for higher level functions such as PrivateSend etc. ....

There is no PoS in its classical meaning in Dash, Masternodes do not participate in the block creation process. They do share the block reward with miners but that's an indirect incentive (there is a deterministic queue). PrivateSend etc. are indeed performed by Masternodes but Masternodes are completely separate full nodes (with no or empty wallet) which share a secret with initial wallets to perform all needed functions (mixing, locking, governance) on their behalf. Collateral funds are not used in these functions directly i.e. initial wallets can stay offline all the time after the setup/upgrade phase is done. This being said, I wouldn't call it PoS. We call this way of incentivising PoSe (Proof-of-Service) and I think this term would fit the note better.

>... Masternodes do not verify the ledger. ...

Masternodes are full nodes and they definitely verify the ledger like any other full nodes, not sure where the confusion came from and why the note says otherwise. This sentence should be removed or clarified (if `verify` means smth else here) imo.

>... There are over 4000 masternodes.

https://github.com/ummjackson/awdy/blob/a7fb4f051cb9373209fec380c25ec297c7090206/_data/coins/dash.yml#L12

In fact, this number (4774) is the number of _active masternodes_ which is slightly lower than the number of _all masternodes_ (4848 according to https://chainz.cryptoid.info/dash/masternodes.dws) which is also lower than the number of _all public nodes_. Unfortunately, I know of no resource which counts _all_ Dash _public nodes_ and not only _masternodes_, so I can't provide a better one atm and I guess it's ok-ish to use it (even though it's not 100% accurate). But maybe this fact (`public_nodes == active_masternodes`) should also be clarified in `notes`.

**Comment by ummjackson** [comment]
Happy to consider a pull request with this information updated.
