### ISSUE TITLE
Mining 'Pools' aren't exactly centralized. Otherwise they'd be called 'mines'. 

### ISSUE THREAD

**Issue by jsgalt** [ummjackson/awdy#8]
Pools, are by definition comprised of users elsewhere, which can point their hashing power elsewhere at any time. otherwise, they are called mines. 

Which means there arn't 3 'entities' with >50% of #Bitcoin mining power. 

There's three agregations of user hashing power, but that's liquid. Any actual hashing power attack could be subverted very fast as soon as danger levels of hashing power centralization got reached or other red flags were seen and announced to the community.

There's clear evidence of this happening with one of the old mining pools which managed to have 51% of Bitcoin hashing power for a few hours, I believe in 2014.

An accurate representation of this would be to differentiate between mines and mining pools.

So how much hashing power does bitmain have in their private legal entity's control, and how much is gathered by antpool through their public pool services? 

It's a very important difference.

**Comment by Gyunikuchan** [comment]
Unless each miner within the pool is global state aware and are adding transactions (no censorship) while doing validations (no double spends), they cannot be considered as independent entities imo...

Sure the argument is that they can move away from badly behaving pools, but by then the damage would've been done. Im also skeptical about the "Any actual hashing power attack could be subverted very fast" sentiment, as many miners are either not technically trained, not aware of the politics involved or simply are not monitoring 24/7 for what his patron pool is doing.

As such each miner is essentially giving away blind votes. I'm personally looking forward to Ethereum's casper which should alleviate this somewhat. Mining pools have turned PoW into dPoW, which is not as bad as dPoS imo, but still not good.

**Comment by jsgalt** [comment]
We have a clear historical event. 

Had more time passed during that Bitcoin fork, and had the attack been intolerable, aka some kind of consensus rule change, then there probably would have been a fork, a block re org of a few hours maybe 2 3 days a la bitcoin cash fork, and the strongest network would have emerged. 

Aka the one with most market confidence. 

people have skin in the game, should not be ignored.

But sure, assuming most of the miners are complacent and not paying attention even with some warning, then bitcoin would be more vulnerable, but so would any other system without some attention. 

Economic incentives would also drive miners to the most confidence attracting chain, and hashing power would dominate one, as weve seen with both ETC ETH and BTC BCH forks. 

its the way of network effects.

**Comment by Gyunikuchan** [comment]
Agree with skin in the game aspect for major breaches of trust. 
But skin in the game is double-edged, and can lead to denial of any criticisms. (As we can clearly see from the current market)

Would you be "feeding the FUD" if there were only a single company's transactions that get intermittently censored? Would the masses chalk it up as the fault of that particular company since it "works fine on mine"?
